language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
install:
  - curl https://sh.rustup.rs -sSf | sh
before_deploy:
  - mkdir build
  - rustup target add x86_64-pc-windows-gnu
  - rustup target add x86_64-apple-darwin
  - rustup target add x86_64-unknown-linux-gnu
  - rustup run stable cargo build --release --target x86_64-pc-windows-gnu
  - cp target/x86_64-pc-windows-gnu/release/csgo-scoreline-monitor.exe build/csgo-scoreline-monitor-win.exe
  - rustup run stable cargo build --release --target x86_64-apple-darwin
  - cp target/x86_64-apple-darwin/release/csgo-scoreline-monitor build/csgo-scoreline-monitor-osx
  - rustup run stable cargo build --release --target x86_64-unknown-linux-gnu
  - cp target/x86_64-unknown-linux-gnu/release/csgo-scoreline-monitor build/csgo-scoreline-monitor-linux
